"""baseline_14_orm_models

Revision ID: 09305d0c17c8
Revises: 
Create Date: 2026-09-20 17:02:51.358480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09305d0c17c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_opportunities_county_id'), 'opportunities', ['county_id'], unique=False)
    op.create_index(op.f('ix_opportunities_created_at'), 'opportunities', ['created_at'], unique=False)
    op.create_index(op.f('ix_opportunities_priority'), 'opportunities', ['priority'], unique=False)
    op.create_index(op.f('ix_opportunities_workflow_stage'), 'opportunities', ['workflow_stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_workflow_stage'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_priority'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_created_at'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_county_id'), table_name='opportunities')
    # ### end Alembic commands ###
