import os
import requests
import json
import time

NOTION_TOKEN = os.environ["NOTION_TOKEN"]
KB_DB_ID = '3e0b5bd1-d90c-812c-9c65-d25cefd633a3'
PIERCE_COUNTY_PAGE_ID = '3e0b5bd1-d90c-814d-af6a-d971b052115d'

headers = {
    'Authorization': f'Bearer {NOTION_TOKEN}',
    'Notion-Version': '2022-06-28',
    'Content-Type': 'application/json'
}

def t(content, bold=False, color="default"):
    return {
        "type": "text",
        "text": {"content": content},
        "annotations": {
            "bold": bold,
            "italic": False,
            "strikethrough": False,
            "underline": False,
            "code": False,
            "color": color
        }
    }

ARTICLES = [
    {
        "title": "Pierce County Court System & LINX Navigation SOP",
        "category": "County Playbook",
        "status": "Approved",
        "source_link": "https://linxonline.co.pierce.wa.us/linxweb/",
        "notes": "Definitive guide to searching, retrieving, and interpreting Pierce County Superior Court probate dockets via LINX.",
        "blocks": [
            {
                "object": "block",
                "type": "heading_1",
                "heading_1": {"rich_text": [t("Pierce County Superior Court & LINX Navigation Guide")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("Jurisdiction: Pierce County Superior Court (County-City Building, 930 Tacoma Ave S, Tacoma, WA 98402). Court records are administered through LINX (Legal Information Network Exchange).")]}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [t("1. Case Number Anatomy (Washington Case Type 4)")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("In Washington State Superior Courts, probate and guardianship matters are filed as "), t("Case Type 4", True), t(". Case numbers follow the format: "), t("YY-4-XXXXX-C", True), t("\n• "), t("YY", True), t(": Two-digit filing year (e.g., 26 for 2026)\n• "), t("4", True), t(": Superior Court Probate/Guardianship Case Type\n• "), t("XXXXX", True), t(": Sequential filing index\n• "), t("C", True), t(": Check digit generated by court software.")]}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [t("2. Navigating the LINX Portal")]}
            },
            {
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": [t("Portal URL: ", True), t("https://linxonline.co.pierce.wa.us/linxweb/")]}
            },
            {
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": [t("Case Search: ", True), t("Search by Litigant Name (decedent last name, first name) or Case Number.")]}
            },
            {
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": [t("Key Docket Codes to Identify: ", True), t("\n  - "), t("PET", True), t(": Petition for Probate of Will and Appointment of Personal Representative\n  - "), t("ORAPW", True), t(": Order Admitting Will to Probate and Appointing PR\n  - "), t("LTR", True), t(": Letters Testamentary (or Letters of Administration) Issued\n  - "), t("NOTCR", True), t(": Notice to Creditors Filed")]}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [t("3. Research Time-Box Budget")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("Standard research time-box: "), t("15 minutes per case file", True), t(". If Letters Testamentary or petition details cannot be confirmed within 15 minutes, flag the case in Tasks & Exceptions and advance to the next candidate.")]}
            }
        ]
    },
    {
        "title": "Washington State Probate Authority Resolution Guide (RCW Title 11)",
        "category": "Authority",
        "status": "Approved",
        "source_link": "https://app.leg.wa.gov/rcw/default.aspx?cite=11",
        "notes": "Statutory legal framework governing authority to sell real estate in Washington State probate.",
        "blocks": [
            {
                "object": "block",
                "type": "heading_1",
                "heading_1": {"rich_text": [t("Washington State Probate Authority Resolution (RCW Title 11)")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("The single most critical factor in probate real estate acquisitions is "), t("Authority Resolution", True), t(": determining whether the party executing the purchase contract has legal authority under Washington law to convey marketable title.")]}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [t("1. Nonintervention Powers (RCW 11.68.011) — The Gold Standard")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("Under RCW 11.68.011, if the decedent's will requests nonintervention powers or if the court finds the estate solvent, the Personal Representative (PR) is granted "), t("Nonintervention Powers", True), t(".")]}
            },
            {
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": [t("Operational Implication: ", True), t("The PR can sell, convey, mortgage, or lease real property "), t("without court approval, notice, or an order confirming sale", True), t(". Closing can occur as rapidly as standard title review permits.")]}
            },
            {
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": [t("Required Documentation: ", True), t("Certified copy of Letters Testamentary with clerk's raised seal + Order Admitting Will granting RCW 11.68 powers.")]}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [t("2. Full Court Intervention Sales (RCW 11.56)")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("When an estate does not have nonintervention powers, sale of real property is strictly regulated:")]}
            },
            {
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": [t("PR must file a formal Petition for Order of Sale under RCW 11.56.030.")]}
            },
            {
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": [t("Court requires notice to all interested parties and a formal hearing.")]}
            },
            {
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": [t("After signing PSA, PR must file a Return of Sale; court must enter an "), t("Order Confirming Sale", True), t(" before deed delivery.")]}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [t("3. Off-Docket & Lack of Probate Affidavit (RCW 82.45.197)")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("When an owner passes away and no probate petition is opened, title can often be cleared via a recorded "), t("Lack of Probate Affidavit", True), t(" accompanied by a certified death certificate under WAC 458-61A-202, provided all heirs consent and title insurance requirements are met.")]}
            }
        ]
    },
    {
        "title": "Pierce County Assessor-Treasurer & GIS Parcel Research Guide",
        "category": "Evidence Standards",
        "status": "Approved",
        "source_link": "https://atip.piercecountywa.gov/",
        "notes": "How to query Pierce County ATIP and the Open Geospatial REST API for parcel validation.",
        "blocks": [
            {
                "object": "block",
                "type": "heading_1",
                "heading_1": {"rich_text": [t("Pierce County Assessor-Treasurer & GIS Parcel Intelligence")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("Pierce County maintains a fully digitized property records infrastructure through the Assessor-Treasurer Information Portal (ATIP) and the ArcGIS Open Geospatial Portal.")]}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [t("1. Tax Parcel Number (APN) Anatomy")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("Pierce County APNs are 10-digit numbers structured by Section, Township, Range, and Quarter-Quarter:\n• "), t("Format: ", True), t("SS-TT-RR-Q-QQ-N (e.g. 0320183042)\n• Direct API Endpoint: "), t("https://services2.arcgis.com/1UvBaQ5y1ubjUPmd/arcgis/rest/services/Tax_Parcels/FeatureServer/0/query", True)]}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [t("2. Key Parcel Attributes")]}
            },
            {
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": [t("Landuse_Description: ", True), t("Identifies property type ('SINGLE FAMILY DWELLING', 'DUPLEX', 'VACANT LAND'). Filter out non-residential parcels.")]}
            },
            {
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": [t("Tax_Senior_Exemption: ", True), t("Flags properties receiving senior/disabled tax reductions under RCW 84.36. Indicates long-term aging-in-place and high probability of equity.")]}
            },
            {
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": [t("TotalMarketValue: ", True), t("Assessed baseline. In Pierce County, wholesale After-Repair-Value (ARV) typically benchmarks at "), t("125% to 145% of total tax assessed value", True), t(".")]}
            }
        ]
    },
    {
        "title": "Pierce County Auditor & Title Recording Records Guide",
        "category": "Ownership",
        "status": "Approved",
        "source_link": "https://www.piercecountywa.gov/398/Auditor",
        "notes": "SOP for title chain verification, deed research, and mortgage encumbrance evaluation.",
        "blocks": [
            {
                "object": "block",
                "type": "heading_1",
                "heading_1": {"rich_text": [t("Pierce County Auditor & Title Chain Intelligence")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("The Pierce County Auditor's Recording Department records all instruments affecting real property, including Deeds, Deeds of Trust (Mortgages), Liens, and Death Certificates.")]}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [t("1. Deed Vesting Types in Pierce County")]}
            },
            {
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": [t("Statutory Warranty Deed: ", True), t("Full warranty of title; standard conveyance in WA.")]}
            },
            {
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": [t("Transfer on Death Deed (TODD): ", True), t("Executed under RCW 64.80. "), t("CRITICAL QC RULE: ", True), t("If a valid TODD was recorded prior to death, the property "), t("passes outside of probate court jurisdiction", True), t(". Disqualify from probate delivery.")]}
            },
            {
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": [t("Personal Representative Deed: ", True), t("The statutory instrument used by the executor to convey title to the buyer at closing.")]}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [t("2. Encumbrance & Mortgage Tracing")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("Trace original Deed of Trust recording date. Properties held 15+ years typically have substantial equity. Check specifically for "), t("Home Equity Conversion Mortgages (HECM / Reverse Mortgages)", True), t("—if balance exceeds market value, file is disqualified in QC.")]}
            }
        ]
    },
    {
        "title": "Pierce County Legal Notices & Creditor Publication Guide (Tacoma Daily Index)",
        "category": "Probate",
        "status": "Approved",
        "source_link": "https://www.tacomadailyindex.com/",
        "notes": "Monitoring notice to creditors and daily probate filings through the official county legal newspaper.",
        "blocks": [
            {
                "object": "block",
                "type": "heading_1",
                "heading_1": {"rich_text": [t("Pierce County Legal Notices & Creditor Publications")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("Under "), t("RCW 11.40.020", True), t(", personal representatives in Washington must publish a formal Notice to Creditors in the official county legal newspaper: the "), t("Tacoma Daily Index", True), t(".")]}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [t("1. The 4-Month Creditor Clock")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("The notice runs once a week for three successive weeks. Creditors have "), t("four months", True), t(" from the date of first publication to present claims. If an estate is solvent and has nonintervention powers, real estate can still be sold during this window, with sale proceeds held in the estate escrow account.")]}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [t("2. Daily Ingestion Utility")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("Monitoring the Tacoma Daily Index provides continuous, real-time discovery of newly opened estates, attorney representations, and appointed personal representatives without requiring LINX portal authentication.")]}
            }
        ]
    },
    {
        "title": "Pierce County Quality Control & Disqualification Standards",
        "category": "Quality Control",
        "status": "Approved",
        "source_link": "https://nutritious-petalite-054.notion.site/3e0b5bd1d90c812c9c65d25cefd633a3",
        "notes": "Strict 5-point quality control rules to guarantee zero unviable files are delivered to clients.",
        "blocks": [
            {
                "object": "block",
                "type": "heading_1",
                "heading_1": {"rich_text": [t("Gieni OS Quality Control & Disqualification Standards")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("Gieni operates under a strict Zero-Garbage output policy. Files that fail any of the following 5 gates are automatically flagged as Disqualified / Rejected.")]}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [t("Gate 1: Real Estate Holdings in Pierce County")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("Approximately 35–40% of probate petitions involve personal property only (bank accounts, vehicles, brokerage assets). If no Pierce County real estate is owned, file is immediately rejected.")]}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [t("Gate 2: Non-Probate Transfer Bypass")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("If title transferred via Transfer on Death Deed (TODD) or Living Trust, title passed outside probate court. Probate PR has no authority to convey.")]}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [t("Gate 3: Equity Spread (LTV < 85%)")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("If senior mortgage, reverse mortgage, or IRS tax liens equal or exceed estimated market value, there is no wholesale equity spread. Disqualify.")]}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [t("Gate 4: Mobile Home on Leased Land Check")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("Verify parcel is fee simple real estate, not personal property mobile home situated on leased park space.")]}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [t("Gate 5: Actionable Authority")]}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [t("Decision maker must be identifiable with clear standing to petition or execute contract.")]}
            }
        ]
    }
]

print("\n--- Populating Knowledge Base for Pierce County, WA ---")
created_articles = 0

for art in ARTICLES:
    props = {
        "Article": {"title": [{"text": {"content": art["title"]}}]},
        "Category": {"select": {"name": art["category"]}},
        "Status": {"select": {"name": art["status"]}},
        "Source Link": {"url": art["source_link"]},
        "Notes": {"rich_text": [{"text": {"content": art["notes"]}}]},
        "County": {"relation": [{"id": PIERCE_COUNTY_PAGE_ID}]}
    }

    payload = {
        "parent": {"database_id": KB_DB_ID},
        "properties": props
    }

    resp = requests.post("https://api.notion.com/v1/pages", headers=headers, json=payload)
    if resp.status_code == 200:
        page_id = resp.json()["id"]
        created_articles += 1
        print(f"[{created_articles}/6] Created Article: {art['title']} (ID: {page_id})")
        
        # Attach rich content blocks
        if art.get("blocks"):
            b_resp = requests.patch(f"https://api.notion.com/v1/blocks/{page_id}/children", headers=headers, json={"children": art["blocks"]})
            if b_resp.status_code != 200:
                print(f"  Warning attaching blocks: {b_resp.status_code}")
    else:
        print(f"Error creating {art['title']}: {resp.status_code} - {resp.text}")

    time.sleep(0.35)

print(f"\nFinished! Successfully created {created_articles} Knowledge Base articles linked to Pierce County.")
